aseguradoraNMA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views
from django.contrib.auth.views import LoginView, LogoutView
from .views import registrar_usuario, mantenedor_usuario, detalle_usuario,crear_usuario,editar_usuario,eliminar_usuario,mantenedor_profesional,crear_profesional,editar_profesional,eliminar_profesional, control_asesoria, crear_checklist,editar_checklist,eliminar_checklist, mantenedor_checklist,registro, index, mantenedor_asesoria, editar_asesoria, eliminar_asesoria, responder_asesoria, planificar_visita,listar_visita,editar_visita, eliminar_visita, servicios, login, crear_capacitacion, listar_capacitacion, editar_capacitacion, eliminar_capacitacion, solicitar_asesoria, mantenedor_asesoria, detalle_asesoria, editar_asesoria2, eliminar_asesoria2, registrar_contrato, mantenedor_contrato, editar_contrato, eliminar_contrato
#usuariocreate

app_name = 'aseguradoraNMA'

urlpatterns = [
    path('', index, name="index"),
    #path('registrar_cliente/',registrar_cliente, name="registrar_cliente"),#ADMINISTRADOR Y PROFESIONAL
    path('login/', LoginView.as_view(template_name='core/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='core/index.html'), name ="logout"),
    path('registro/',registro, name="registro"),
    path('registrar_usuario', registrar_usuario, name="registrar_usuario"),#ADMINISTRADOR
    path('mantenedor_usuario/', views.mantenedor_usuario, name = 'mantenedor_usuario'), #PROFESIONAL
    path('detalle_usuario_<int:id>/', views.detalle_usuario, name = 'detalle_usuario'), #PROFESIONAL
    #path('detalle_cliente_<int:id>/', views.detalle_cliente, name = 'detalle_cliente'), #PROFESIONAL
    path('crear_usuario/', views.crear_usuario , name = 'crear_usuario'), #PROFESIONAL
    path('editar_usuario_<int:id>/' , views.editar_usuario , name = 'editar_usuario'), #PROFESIONAL
    path('eliminar_usuario_<int:id>/' , views.eliminar_usuario , name = 'eliminar_usuario'), #PROFESIONAL
    path('mantenedor_profesional/', views.mantenedor_profesional, name = 'mantenedor_profesional'), #PROFESIONAL
    path('crear_profesional/', views.crear_profesional , name = 'crear_profesional'), #PROFESIONAL
    path('editar_profesional_<int:id>/' , views.editar_profesional , name = 'editar_profesional'), #PROFESIONAL
    path('eliminar_profesional_<int:id>/' , views.eliminar_profesional , name = 'eliminar_profesional'), #PROFESIONAL
    path('servicios/', servicios, name="servicios"), #SERVICIOS
    path('crear_capacitacion/', crear_capacitacion, name="crear_capacitacion"),
    path('listar_capacitacion/', listar_capacitacion, name="listar_capacitacion"),
    path('editar_capacitacion/<id>/', editar_capacitacion, name="editar_capacitacion"),
    path('eliminar_capacitacion/<id>/', eliminar_capacitacion, name="eliminar_capacitacion"),
    path('planificar_visita/', planificar_visita, name="planificar_visita"),
    path('mantenedor_visita/', listar_visita, name="mantenedor_visita"),
    path('editar_visita/<id>/', editar_visita, name="editar_visita"),
    path('eliminar_visita/<id>/', eliminar_visita, name="eliminar_visita"),
    path('solicitar_asesoria/', solicitar_asesoria, name="solicitar_asesoria"),
    path('mantenedor_asesoria/', mantenedor_asesoria, name="mantenedor_asesoria"),
    path('editar_asesoria/<id>/', editar_asesoria, name="editar_asesoria"),
    path('detalle_asesoria/<id>/', detalle_asesoria, name="detalle_asesoria"),
    path('eliminar_asesoria/<id>/', eliminar_asesoria, name="eliminar_asesoria"),
    path('responder_asesoria/', responder_asesoria, name="responder_asesoria"),
    path('asesorias_respondidas/', control_asesoria, name="asesorias_respondidas"),
    path('editar_asesoria2/<id>/', editar_asesoria2, name="editar_asesoria2"),
    path('eliminar_asesoria2/<id>/', eliminar_asesoria2, name="eliminar_asesoria2"),
    path('mi_informacion/', control_asesoria, name="mi_informacion"),
    path('mantenedor_profesional/', views.mantenedor_profesional, name = 'mantenedor_profesional'),
    path('crear_checklist/', crear_checklist, name="crear_checklist"),
    path('editar_checklist_<int:id>/' , views.editar_checklist , name = 'editar_checklist'), 
    path('eliminar_checklist_<int:id>/' , views.eliminar_checklist , name = 'eliminar_checklist'),
    path('mantenedor_checklist/', mantenedor_checklist, name="mantenedor_checklist"),
    path('registrar_contrato/', registrar_contrato, name="registrar_contrato"),
    path('mantenedor_contrato/', mantenedor_contrato, name="mantenedor_contrato"),
    path('editar_contrato/<id>/', editar_contrato, name="editar_contrato"),
    path('eliminar_contrato/<id>/', eliminar_contrato, name="eliminar_contrato"),
]

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, ListView, View
from django.http import HttpResponseRedirect, HttpResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from .models import Asignar_asesoria, Capacitacion,Visita, Solicitar_asesoria, Checklist, Usuario, Profesional, Contrato
from .forms import  CapacitacionForm, UsuarioModelForm, VisitaForm, SolicitarasesoriaForm, Asignar_asesoriaForm, ChecklistForm, ProfesionalForm, ContratoForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login as ingresar, logout
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request, "core/index.html")

def servicios(request):
    return render(request, "core/servicios.html")

def login(request):
    return render(request, "core/login.html")

def registro(request):   
    if request.method == 'POST':
        form = UsuarioModelForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'Usuario {username} Creado')
    else:
        form = UsuarioModelForm()
    
    context = {'form' : form }
    return render(request,'core/Registros/registro.html', context)
        

def registrar_usuario(request):
    if request.method == "POST" : 
        form = UsuarioModelForm(request.POST)
        if form.is_valid() : 
            form.save()
            messages.success(request, "creado correctamente")
            return redirect('aseguradoraNMA:index')
    else :
            form = UsuarioModelForm()
    return render(request , 'core/Registros/registrar_usuario.html' , {'form' : form})


def mantenedor_usuario(request):
    usuario = Usuario.objects.all()
    context = {
        'usuario' : usuario
    } 
    return render(request, 'core/Mantenedores/mantenedor_usuario.html', context)

def detalle_usuario(request , id) :
    detalle_usuario = get_object_or_404(Usuario , pk = id)
    context = {
        'detalle_usuario' : detalle_usuario
    }
    return render(request ,'core/Mantenedores/detalle_usuario.html', context)

#def detalle_cliente(request , id) :
#    detalle_cliente = get_object_or_404(Usuario , pk = id)
#    context = {
#        'detalle_cliente' : detalle_cliente
#    }
#    return render(request ,'core/Cliente/detalle_cliente.html', context)

def crear_usuario(request) :
    if request.method == "POST" : 
        form = UsuarioModelForm(request.POST)
        if form.is_valid() : 
            form.save()
            messages.success(request, "creado correctamente")
            return redirect('aseguradoraNMA:mantenedor_usuario')
    else :
            form = UsuarioModelForm()
    return render(request , 'core/Mantenedores/crear_usuario.html' , {'form' : form})

def editar_usuario(request , id) :
    usuario = get_object_or_404(Usuario , id = id)
    data = {
        'form': UsuarioModelForm(instance=usuario)
    }

    if request.method == "POST" :
        usuario_form = UsuarioModelForm(data=request.POST , instance=usuario, files=request.FILES)
        if usuario_form.is_valid() :
            usuario_form.save()
            messages.success(request, "modificado correctamente")
            return redirect('aseguradoraNMA:mantenedor_usuario')
        data["form"] = usuario_form

    return render(request, 'core/Mantenedores/editar_usuario.html', data)
    
def eliminar_usuario(request , id) :
    usuario = get_object_or_404(Usuario , id = id)

    if usuario : 
        usuario.delete()
        messages.success(request, "eliminado correctamente")
        return redirect('aseguradoraNMA:mantenedor_usuario')

#LISTADO DE PROFESIONALES
def mantenedor_profesional(request):
    profesional = Profesional.objects.all()
    context = {
        'profesional' : profesional
    } 
    return render(request, 'core/Mantenedores/mantenedor_profesional.html', context)

#def detalle_usuario(request , id) :
#    detalle_usuario = get_object_or_404(Usuario , pk = id)
#    context = {
#        'detalle_usuario' : detalle_usuario
#    }
#    return render(request ,'core/Mantenedores/detalle_usuario.html', context)

def crear_profesional(request) :
    if request.method == "POST" : 
        form = ProfesionalForm(request.POST)
        if form.is_valid() : 
            form.save()
            messages.success(request, "creado correctamente")
            return redirect('aseguradoraNMA:mantenedor_profesional')
    else :
            form = ProfesionalForm()
    return render(request , 'core/Mantenedores/crear_profesional.html' , {'form' : form})

def editar_profesional(request , id) :
    profesional = get_object_or_404(Profesional , id = id)
    data = {
        'form': ProfesionalForm(instance=profesional)
    }

    if request.method == "POST" :
        form = ProfesionalForm(data=request.POST , instance=profesional, files=request.FILES)
        if form.is_valid() :
            form.save()
            messages.success(request, "modificado correctamente")
            return redirect('aseguradoraNMA:mantenedor_profesional')
        data["form"] = form

    return render(request, 'core/Mantenedores/editar_profesional.html', data)
    
def eliminar_profesional(request , id) :
    profesional = get_object_or_404(Profesional , id = id)

    if profesional : 
        profesional.delete()
        messages.success(request, "eliminado correctamente")
        return redirect('aseguradoraNMA:mantenedor_profesional')

#CAPACITACIONES
def crear_capacitacion(request):

    data = {
        'form': CapacitacionForm()
    }
    if request.method == "POST" : 
        formulario = CapacitacionForm(request.POST)
        if formulario.is_valid() : 
            formulario.save()
            messages.success(request, "creada correctamente")
            return redirect('aseguradoraNMA:listar_capacitacion')
    return render(request, 'core/Capacitaciones/crear_capacitacion.html', data)

def listar_capacitacion(request):
    capacitaciones = Capacitacion.objects.all()
    data = {
        'capacitaciones' : capacitaciones
    }
    return render(request, 'core/Capacitaciones/listar_capacitacion.html', data)

def editar_capacitacion(request, id):

    capacitaciones = get_object_or_404(Capacitacion, id=id)

    data = {
        'form': CapacitacionForm(instance=capacitaciones)
    }

    if request.method == 'POST':
        formulario = CapacitacionForm(data=request.POST, instance=capacitaciones, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "modificado correctamente")
            return redirect('aseguradoraNMA:listar_capacitacion')
        data["form"] = formulario

    return render(request, 'core/Capacitaciones/editar_capacitacion.html',data)

def eliminar_capacitacion(request, id):
    capacitaciones = get_object_or_404(Capacitacion, id=id)
    capacitaciones.delete()
    messages.success(request, "eliminado correctamente")
    return redirect('aseguradoraNMA:listar_capacitacion')

#PLANIFICAR VISITA
def planificar_visita(request):

    data = {
        'form': VisitaForm()
    }
    if request.method == "POST" : 
        formulario = VisitaForm(request.POST)
        if formulario.is_valid() : 
            formulario.save()
            messages.success(request, "registrado correctamente")
            return redirect('aseguradoraNMA:mantenedor_visita')
    return render(request, 'core/Visitas/planificar_visita.html', data)

def listar_visita(request):
    visitas = Visita.objects.all()
    data = {
        'visitas' : visitas
    }
    return render(request, 'core/Visitas/mantenedor_visita.html', data)

def editar_visita(request, id):

    visitas = get_object_or_404(Visita, id=id)

    data = {
        'form': VisitaForm(instance=visitas)
    }

    if request.method == 'POST':
        formulario = VisitaForm(data=request.POST, instance=visitas, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "editado correctamente")
            return redirect('aseguradoraNMA:mantenedor_visita')
        data["form"] = formulario

    return render(request, 'core/Visitas/editar_visita.html',data)

def eliminar_visita(request, id):
    visitas = get_object_or_404(Visita, id=id)
    visitas.delete()
    messages.success(request, "eliminado correctamente")
    return redirect('aseguradoraNMA:mantenedor_visita')

def mantenedor_checklist(request):
    checklist = Checklist.objects.all()
    data = {
        'checklist' : checklist
    }
    return render(request, 'core/Visitas/mantenedor_checklist.html', data)

def crear_checklist(request):

    data = {
        'form': ChecklistForm()
    }
    if request.method == "POST" : 
        formulario = ChecklistForm(request.POST)
        if formulario.is_valid() : 
            formulario.save()
            messages.success(request, "creado correctamente")
    return render(request, 'core/Visitas/crear_checklist.html', data)

def editar_checklist(request , id) :
    checklist = get_object_or_404(Checklist , id = id)
    data = {
        'form': ChecklistForm(instance=checklist)
    }

    if request.method == "POST" :
        form = ChecklistForm(data=request.POST , instance=checklist, files=request.FILES)
        if form.is_valid() :
            form.save()
            messages.success(request, "modificado correctamente")
            return redirect('aseguradoraNMA:mantenedor_checklist')
        data["form"] = form

    return render(request, 'core/Visitas/editar_checklist.html', data)
    
def eliminar_checklist(request , id) :
    checklist = get_object_or_404(Checklist , id = id)

    if checklist : 
        checklist.delete()
        messages.success(request, "eliminado correctamente")
        return redirect('aseguradoraNMA:mantenedor_checklist')

#SOLICITAR ASESORIAS

core/templates/core/Asesorias/asesorias_respondidas.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Gestion de Asesorias Respondidas</title>
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/mantenedor.css' %}">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>
<br></br>
<body>
    <div class="card">
        <div class="card-body">
            <h2> Asesorias Respondidas</h2>
            <br></br>
            <table class="table table-striped table-hover table-responsive">
                <tr>
                    <th>ID Asesoria </th>
                    <th>Datos Asesoria</th>
                    <th>Profesional Asignado</th>
                    <th>Gestion Accidente</th>
                    <th>Mejoras Propuestas</th>
                    <th>Informacion de Evento</th>
                    <th>Diligencias Asociadas</th>
                    <th>Juicios Asociados</th>
                    <th>Asesoria Completada</th>
                    <th>Opciones</th>
                </tr>
                {% for p in asesorias %}
            
                <tr>
                    <td>{{ p.id  | title }}</td>
                    <td>{{ p.Solicitar_asesoria| title }}</td>
                    <td>{{ p.Profesional | title }}</td>
                    <td>{{ p.gestion_accidentes | title }}</td>
                    <td>{{ p.mejoras_propuestas | title }}</td>
                    <td>{{ p.info_evento | title }}</td>
                    <td>{{ p.diligencias_asociadas | title }}</td>
                    <td>{{ p.juicios_asociados | title }}</td>
                    <td>{% if p.estado_asesoria %}
                        SI
                        {% else %}
                        NO
                        {% endif %}
                    </td> 

                    <td>
                        <a href="{% url 'aseguradoraNMA:editar_asesoria2' p.id %}" class="btn btn-info btn-sm">Modificar</a>
                        <h2></h2>
                        <a href="{% url 'aseguradoraNMA:eliminar_asesoria2' p.id %}" class="btn btn-info btn-sm">Eliminar</a>
                    </td>
                </tr>
            
                {% endfor %}
            
            </table>
            <div class="d-flex justify-content-end">
                <a href="{% url 'aseguradoraNMA:mantenedor_asesoria' %}" class="btn btn btn-primary">Volver</a>
                &nbsp;
                <!--<a href="{% url 'aseguradoraNMA:responder_asesoria' %}" class="btn btn btn-primary">Crear Nueva</a>-->
            </div>
        </div>
    </div>
    <div id="contenido">
        {% if messages %}
            {% for m in messages %}
            <script>
                Swal.fire({
                    "title":"Proceso Realizado",
                    "text": "{{m}}",
                    "icon": "success"
                })
            </script>
            {% endfor %}
        {% endif %}
    </div>
</body>

core/templates/core/Asesorias/detalle_asesoria.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Detalle Cliente</title>
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
    

</head>
<body>
<br></br>
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
<center><h2>Detalle Asesoria</h2><center>
<div class="container">
<p>{{ detalle_asesoria.id }}</p>
<p>{{ detalle_asesoria.fecha_asesoria}}</p>
<p>{{ detalle_asesoria.hora_asesoria }}</p>
<p>{{ detalle_asesoria.nombre_cliente }}</p>
<p>{{ detalle_asesoria.rut_cliente }}</p>
<p>{{ detalle_asesoria.tipo_asesoria }}</p>
<p>{{ detalle_asesoria.problemas_encontrados }}</p>
<p>{{ detalle_asesoria.asistentes }}</p>
</div>
</div>
<a href="{% url 'aseguradoraNMA:mantenedor_asesoria' %}" class="btn btn btn-primary">Volver a Mantenedor</a>
</div>
</div>
</div>
</body>

core/templates/core/Asesorias/editar_asesoria.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Editar Asesorias</title>
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>
<body>
<br></br>
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <h2>Editar Asesorias</h2>
                        <hr>
                <form action="" method="post">

                    {% csrf_token %}
                    <table>
                    {{ form | crispy }}
                    </table>
                    <br></br>
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'aseguradoraNMA:mantenedor_asesoria' %}" class="btn btn btn-primary">Volver al Listado</a>
                        &nbsp;
                        <input type="reset" value="Cancelar" class="btn btn-primary">
                        &nbsp;
                        <input type="submit" value="Guardar" class="btn btn-primary">
                        
                        
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
<div id="contenido">
    {% if messages %}
        {% for m in messages %}
        <script>
            Swal.fire({
                "title":"Proceso Realizado",
                "text": "{{m}}",
                "icon": "success"
            })
        </script>
        {% endfor %}
    {% endif %}
</div>
</body>

core/templates/core/Asesorias/mantenedor_asesoria.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Lista de Asesorias Solicitadas</title>
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/mantenedor.css' %}">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>
<br></br>
<body>
    <div class="card">
        <div class="card-body">
            <h2> Listado de Asesorias Solicitadas</h2>
            <br></br>
            <table class="table table-striped table-hover table-responsive">
                <tr>
                    <th>ID Asesoria</th>
                    <th>Fecha Asesoria</th>
                    <th>Hora Asesoria</th>
                    <th>Tipo Asesoria</th>
                    <th>Problemas Encontrados</th>
                    <th>Asistentes</th>
                    <th>Opciones</th>
                </tr>
                {% for p in asesorias %}
            
                <tr>
                    <td>{{ p.id  | title }}</td>
                    <td>{{ p.fecha_asesoria| title }}</td>
                    <td>{{ p.hora_asesoria | title }}</td>
                    <td>{{ p.tipo_asesoria | title }}</td>
                    <td>{{ p.problemas_encontrados | title }}</td> 
                    <td>{{ p.asistentes | title }}</td>
                    <td>
                        <a href="{% url 'aseguradoraNMA:editar_asesoria' p.id %}" class="btn btn-info btn-sm">Modificar</a>
                        <h2></h2>
                        <a href="{% url 'aseguradoraNMA:detalle_asesoria' p.id %}" class="btn btn-info btn-sm">Detalle</a>
                        <h2></h2>
                        <a href="{% url 'aseguradoraNMA:eliminar_asesoria' p.id %}" class="btn btn-info btn-sm">Eliminar</a>
                    </td>
                </tr>
            
                {% endfor %}
            
            </table>
            <div class="d-flex justify-content-end">
                <a href="{% url 'aseguradoraNMA:index' %}" class="btn btn btn-primary">Volver a Inicio</a>
                &nbsp;
                <a href="{% url 'aseguradoraNMA:asesorias_respondidas' %}" class="btn btn btn-primary">Lista de Asesorias Respondidas</a>
                &nbsp;
                <a href="{% url 'aseguradoraNMA:responder_asesoria' %}" class="btn btn btn-primary">Responder Asesorias</a>
            </div>
        </div>
    </div>
    <div id="contenido">
        {% if messages %}
            {% for m in messages %}
            <script>
                Swal.fire({
                    "title":"Proceso Realizado",
                    "text": "{{m}}",
                    "icon": "success"
                })
            </script>
            {% endfor %}
        {% endif %}
    </div>
</body>

core/templates/core/Asesorias/responder_asesoria.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Responder Asesorias </title>
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/estilos.css' %}">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>
<body>
<br></br>
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <h2>Responder Asesorias</h2>
                        <hr>
                <form action="" method="post">

                    {% csrf_token %}
                    <table>
                    {{ form.as_p }}
                    </table>
                    <br></br>
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'aseguradoraNMA:index' %}" class="btn btn btn-primary">Ir a Inicio</a>
                        &nbsp;
                        <a href="{% url 'aseguradoraNMA:asesorias_respondidas' %}" class="btn btn btn-primary">Ir al Listado</a>
                        &nbsp;
                        <input type="reset" value="Cancelar" class="btn btn-primary">
                        &nbsp;
                        <input type="submit" value="Guardar" class="btn btn-primary">
                    </div>
                    
                </form>
            </div>
        </div>

    </div>
</div>
<div id="contenido">
    {% if messages %}
        {% for m in messages %}
        <script>
            Swal.fire({
                "title":"Proceso Realizado",
                "text": "{{m}}",
                "icon": "success"
            })
        </script>
        {% endfor %}
    {% endif %}
</div>
</body>

core/templates/core/Asesorias/solicitar_asesoria.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Solicitar Asesoria</title>
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/registros.css' %}">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>
<body>
<br></br>
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <h2>Solicitar Asesoria</h2>
                        <hr>
                <form action="" method="post">

                    {% csrf_token %}
                    <table>
                    {{ form | crispy }}
                    </table>
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'aseguradoraNMA:index' %}" class="btn btn btn-primary">Ir a Inicio</a>
                        &nbsp;
                        <input type="reset" value="Cancelar" class="btn btn-primary">
                        &nbsp;
                        <input type="submit" value="Guardar" class="btn btn-primary">
                    </div>
                    
                </form>
            </div>
        </div>

    </div>
</div>
<div id="contenido">
    {% if messages %}
        {% for m in messages %}
        <script>
            Swal.fire({
                "title":"Proceso Realizado",
                "text": "{{m}}",
                "icon": "success"
            })
        </script>
        {% endfor %}
    {% endif %}
</div>
</body>