aseguradoraNMA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core import views
from django.contrib.auth.views import LoginView, LogoutView
from .views import registrar_usuario, mantenedor_usuario, detalle_usuario,crear_usuario,editar_usuario,eliminar_usuario,mantenedor_profesional,crear_profesional,editar_profesional,eliminar_profesional, control_asesoria, crear_checklist,editar_checklist,eliminar_checklist, mantenedor_checklist,registro, index, mantenedor_asesoria, editar_asesoria, eliminar_asesoria, responder_asesoria, planificar_visita,listar_visita,editar_visita, eliminar_visita, servicios, login, crear_capacitacion, listar_capacitacion, editar_capacitacion, eliminar_capacitacion, solicitar_asesoria, mantenedor_asesoria, detalle_asesoria, editar_asesoria2, eliminar_asesoria2, registrar_contrato, mantenedor_contrato, editar_contrato, eliminar_contrato
#usuariocreate

app_name = 'aseguradoraNMA'

urlpatterns = [
    path('', index, name="index"),
    #path('registrar_cliente/',registrar_cliente, name="registrar_cliente"),#ADMINISTRADOR Y PROFESIONAL
    path('login/', LoginView.as_view(template_name='core/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='core/index.html'), name ="logout"),
    path('registro/',registro, name="registro"),
    path('registrar_usuario', registrar_usuario, name="registrar_usuario"),#ADMINISTRADOR
    path('mantenedor_usuario/', views.mantenedor_usuario, name = 'mantenedor_usuario'), #PROFESIONAL
    path('detalle_usuario_<int:id>/', views.detalle_usuario, name = 'detalle_usuario'), #PROFESIONAL
    #path('detalle_cliente_<int:id>/', views.detalle_cliente, name = 'detalle_cliente'), #PROFESIONAL
    path('crear_usuario/', views.crear_usuario , name = 'crear_usuario'), #PROFESIONAL
    path('editar_usuario_<int:id>/' , views.editar_usuario , name = 'editar_usuario'), #PROFESIONAL
    path('eliminar_usuario_<int:id>/' , views.eliminar_usuario , name = 'eliminar_usuario'), #PROFESIONAL
    path('mantenedor_profesional/', views.mantenedor_profesional, name = 'mantenedor_profesional'), #PROFESIONAL
    path('crear_profesional/', views.crear_profesional , name = 'crear_profesional'), #PROFESIONAL
    path('editar_profesional_<int:id>/' , views.editar_profesional , name = 'editar_profesional'), #PROFESIONAL
    path('eliminar_profesional_<int:id>/' , views.eliminar_profesional , name = 'eliminar_profesional'), #PROFESIONAL
    path('servicios/', servicios, name="servicios"), #SERVICIOS
    path('crear_capacitacion/', crear_capacitacion, name="crear_capacitacion"),
    path('listar_capacitacion/', listar_capacitacion, name="listar_capacitacion"),
    path('editar_capacitacion/<id>/', editar_capacitacion, name="editar_capacitacion"),
    path('eliminar_capacitacion/<id>/', eliminar_capacitacion, name="eliminar_capacitacion"),
    path('planificar_visita/', planificar_visita, name="planificar_visita"),
    path('mantenedor_visita/', listar_visita, name="mantenedor_visita"),
    path('editar_visita/<id>/', editar_visita, name="editar_visita"),
    path('eliminar_visita/<id>/', eliminar_visita, name="eliminar_visita"),
    path('solicitar_asesoria/', solicitar_asesoria, name="solicitar_asesoria"),
    path('mantenedor_asesoria/', mantenedor_asesoria, name="mantenedor_asesoria"),
    path('editar_asesoria/<id>/', editar_asesoria, name="editar_asesoria"),
    path('detalle_asesoria/<id>/', detalle_asesoria, name="detalle_asesoria"),
    path('eliminar_asesoria/<id>/', eliminar_asesoria, name="eliminar_asesoria"),
    path('responder_asesoria/', responder_asesoria, name="responder_asesoria"),
    path('asesorias_respondidas/', control_asesoria, name="asesorias_respondidas"),
    path('editar_asesoria2/<id>/', editar_asesoria2, name="editar_asesoria2"),
    path('eliminar_asesoria2/<id>/', eliminar_asesoria2, name="eliminar_asesoria2"),
    path('mi_informacion/', control_asesoria, name="mi_informacion"),
    path('mantenedor_profesional/', views.mantenedor_profesional, name = 'mantenedor_profesional'),
    path('crear_checklist/', crear_checklist, name="crear_checklist"),
    path('editar_checklist_<int:id>/' , views.editar_checklist , name = 'editar_checklist'), 
    path('eliminar_checklist_<int:id>/' , views.eliminar_checklist , name = 'eliminar_checklist'),
    path('mantenedor_checklist/', mantenedor_checklist, name="mantenedor_checklist"),
    path('registrar_contrato/', registrar_contrato, name="registrar_contrato"),
    path('mantenedor_contrato/', mantenedor_contrato, name="mantenedor_contrato"),
    path('editar_contrato/<id>/', editar_contrato, name="editar_contrato"),
    path('eliminar_contrato/<id>/', eliminar_contrato, name="eliminar_contrato"),
]

core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, ListView, View
from django.http import HttpResponseRedirect, HttpResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from .models import Asignar_asesoria, Capacitacion,Visita, Solicitar_asesoria, Checklist, Usuario, Profesional, Contrato
from .forms import  CapacitacionForm, UsuarioModelForm, VisitaForm, SolicitarasesoriaForm, Asignar_asesoriaForm, ChecklistForm, ProfesionalForm, ContratoForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login as ingresar, logout
from django.contrib import messages

# Create your views here.

def index(request):
    return render(request, "core/index.html")

def servicios(request):
    return render(request, "core/servicios.html")

def login(request):
    return render(request, "core/login.html")

def registro(request):   
    if request.method == 'POST':
        form = UsuarioModelForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f'Usuario {username} Creado')
    else:
        form = UsuarioModelForm()
    
    context = {'form' : form }
    return render(request,'core/Registros/registro.html', context)
        

def registrar_usuario(request):
    if request.method == "POST" : 
        form = UsuarioModelForm(request.POST)
        if form.is_valid() : 
            form.save()
            messages.success(request, "creado correctamente")
            return redirect('aseguradoraNMA:index')
    else :
            form = UsuarioModelForm()
    return render(request , 'core/Registros/registrar_usuario.html' , {'form' : form})


def mantenedor_usuario(request):
    usuario = Usuario.objects.all()
    context = {
        'usuario' : usuario
    } 
    return render(request, 'core/Mantenedores/mantenedor_usuario.html', context)

def detalle_usuario(request , id) :
    detalle_usuario = get_object_or_404(Usuario , pk = id)
    context = {
        'detalle_usuario' : detalle_usuario
    }
    return render(request ,'core/Mantenedores/detalle_usuario.html', context)

#def detalle_cliente(request , id) :
#    detalle_cliente = get_object_or_404(Usuario , pk = id)
#    context = {
#        'detalle_cliente' : detalle_cliente
#    }
#    return render(request ,'core/Cliente/detalle_cliente.html', context)

def crear_usuario(request) :
    if request.method == "POST" : 
        form = UsuarioModelForm(request.POST)
        if form.is_valid() : 
            form.save()
            messages.success(request, "creado correctamente")
            return redirect('aseguradoraNMA:mantenedor_usuario')
    else :
            form = UsuarioModelForm()
    return render(request , 'core/Mantenedores/crear_usuario.html' , {'form' : form})

def editar_usuario(request , id) :
    usuario = get_object_or_404(Usuario , id = id)
    data = {
        'form': UsuarioModelForm(instance=usuario)
    }

    if request.method == "POST" :
        usuario_form = UsuarioModelForm(data=request.POST , instance=usuario, files=request.FILES)
        if usuario_form.is_valid() :
            usuario_form.save()
            messages.success(request, "modificado correctamente")
            return redirect('aseguradoraNMA:mantenedor_usuario')
        data["form"] = usuario_form

    return render(request, 'core/Mantenedores/editar_usuario.html', data)
    
def eliminar_usuario(request , id) :
    usuario = get_object_or_404(Usuario , id = id)

    if usuario : 
        usuario.delete()
        messages.success(request, "eliminado correctamente")
        return redirect('aseguradoraNMA:mantenedor_usuario')

#LISTADO DE PROFESIONALES
def mantenedor_profesional(request):
    profesional = Profesional.objects.all()
    context = {
        'profesional' : profesional
    } 
    return render(request, 'core/Mantenedores/mantenedor_profesional.html', context)

#def detalle_usuario(request , id) :
#    detalle_usuario = get_object_or_404(Usuario , pk = id)
#    context = {
#        'detalle_usuario' : detalle_usuario
#    }
#    return render(request ,'core/Mantenedores/detalle_usuario.html', context)

def crear_profesional(request) :
    if request.method == "POST" : 
        form = ProfesionalForm(request.POST)
        if form.is_valid() : 
            form.save()
            messages.success(request, "creado correctamente")
            return redirect('aseguradoraNMA:mantenedor_profesional')
    else :
            form = ProfesionalForm()
    return render(request , 'core/Mantenedores/crear_profesional.html' , {'form' : form})

def editar_profesional(request , id) :
    profesional = get_object_or_404(Profesional , id = id)
    data = {
        'form': ProfesionalForm(instance=profesional)
    }

    if request.method == "POST" :
        form = ProfesionalForm(data=request.POST , instance=profesional, files=request.FILES)
        if form.is_valid() :
            form.save()
            messages.success(request, "modificado correctamente")
            return redirect('aseguradoraNMA:mantenedor_profesional')
        data["form"] = form

    return render(request, 'core/Mantenedores/editar_profesional.html', data)
    
def eliminar_profesional(request , id) :
    profesional = get_object_or_404(Profesional , id = id)

    if profesional : 
        profesional.delete()
        messages.success(request, "eliminado correctamente")
        return redirect('aseguradoraNMA:mantenedor_profesional')

#CAPACITACIONES
def crear_capacitacion(request):

    data = {
        'form': CapacitacionForm()
    }
    if request.method == "POST" : 
        formulario = CapacitacionForm(request.POST)
        if formulario.is_valid() : 
            formulario.save()
            messages.success(request, "creada correctamente")
            return redirect('aseguradoraNMA:listar_capacitacion')
    return render(request, 'core/Capacitaciones/crear_capacitacion.html', data)

def listar_capacitacion(request):
    capacitaciones = Capacitacion.objects.all()
    data = {
        'capacitaciones' : capacitaciones
    }
    return render(request, 'core/Capacitaciones/listar_capacitacion.html', data)

def editar_capacitacion(request, id):

    capacitaciones = get_object_or_404(Capacitacion, id=id)

    data = {
        'form': CapacitacionForm(instance=capacitaciones)
    }

    if request.method == 'POST':
        formulario = CapacitacionForm(data=request.POST, instance=capacitaciones, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "modificado correctamente")
            return redirect('aseguradoraNMA:listar_capacitacion')
        data["form"] = formulario

    return render(request, 'core/Capacitaciones/editar_capacitacion.html',data)

def eliminar_capacitacion(request, id):
    capacitaciones = get_object_or_404(Capacitacion, id=id)
    capacitaciones.delete()
    messages.success(request, "eliminado correctamente")
    return redirect('aseguradoraNMA:listar_capacitacion')

#PLANIFICAR VISITA
def planificar_visita(request):

    data = {
        'form': VisitaForm()
    }
    if request.method == "POST" : 
        formulario = VisitaForm(request.POST)
        if formulario.is_valid() : 
            formulario.save()
            messages.success(request, "registrado correctamente")
            return redirect('aseguradoraNMA:mantenedor_visita')
    return render(request, 'core/Visitas/planificar_visita.html', data)

def listar_visita(request):
    visitas = Visita.objects.all()
    data = {
        'visitas' : visitas
    }
    return render(request, 'core/Visitas/mantenedor_visita.html', data)

def editar_visita(request, id):

    visitas = get_object_or_404(Visita, id=id)

    data = {
        'form': VisitaForm(instance=visitas)
    }

    if request.method == 'POST':
        formulario = VisitaForm(data=request.POST, instance=visitas, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "editado correctamente")
            return redirect('aseguradoraNMA:mantenedor_visita')
        data["form"] = formulario

    return render(request, 'core/Visitas/editar_visita.html',data)

def eliminar_visita(request, id):
    visitas = get_object_or_404(Visita, id=id)
    visitas.delete()
    messages.success(request, "eliminado correctamente")
    return redirect('aseguradoraNMA:mantenedor_visita')

def mantenedor_checklist(request):
    checklist = Checklist.objects.all()
    data = {
        'checklist' : checklist
    }
    return render(request, 'core/Visitas/mantenedor_checklist.html', data)

def crear_checklist(request):

    data = {
        'form': ChecklistForm()
    }
    if request.method == "POST" : 
        formulario = ChecklistForm(request.POST)
        if formulario.is_valid() : 
            formulario.save()
            messages.success(request, "creado correctamente")
    return render(request, 'core/Visitas/crear_checklist.html', data)

def editar_checklist(request , id) :
    checklist = get_object_or_404(Checklist , id = id)
    data = {
        'form': ChecklistForm(instance=checklist)
    }

    if request.method == "POST" :
        form = ChecklistForm(data=request.POST , instance=checklist, files=request.FILES)
        if form.is_valid() :
            form.save()
            messages.success(request, "modificado correctamente")
            return redirect('aseguradoraNMA:mantenedor_checklist')
        data["form"] = form

    return render(request, 'core/Visitas/editar_checklist.html', data)
    
def eliminar_checklist(request , id) :
    checklist = get_object_or_404(Checklist , id = id)

    if checklist : 
        checklist.delete()
        messages.success(request, "eliminado correctamente")
        return redirect('aseguradoraNMA:mantenedor_checklist')

#SOLICITAR ASESORIAS

core/templates/core/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    {% load static %}
    {% load crispy_forms_tags %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway|Ubuntu" rel="stylesheet">

    <!-- Estilos -->
    <link rel="stylesheet" href="{% static 'core/css/registros.css' %}">
    <title>Iniciar Sesion</title>
</head>
<body>
    <div class="signupFrm">
        <form action="{% url 'aseguradoraNMA:login' %}" class="form" method="post">
          {% csrf_token %}
          <center><h1 class="title">Iniciar Sesión</h1>
          </center>
       

          <div class="inputContainer">
            <input type="text" name="username" class="input" placeholder="usuario">
            <label for="" class="label">Usuario</label>
          </div>

          <div class="inputContainer">
            <input type="password" name="password" class="input" placeholder="Contraseña">
            <label for="" class="label">Contraseña</label>
          </div>

          <input type="submit" class="submitBtn" value="Entrar">
          <a href="{% url 'aseguradoraNMA:registro' %}" class="btn btn-primary btn-sm">Registrate</a> | 
          <a href="{% url 'aseguradoraNMA:index' %}" class="btn btn-primary btn-sm">Volver a Inicio</a>
        </form>
      </div>
    </div>
</body>

core/templates/core/servicios.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with Ollie landing page.">
    <meta name="author" content="Devcrud">
    <title>Servicios NMA</title>
    {% load static %}
    <!-- font icons -->
    <link rel="stylesheet" href="{% static 'core/vendors/themify-icons/css/themify-icons.css' %}">
    
    <!-- owl carousel -->
    <link rel="stylesheet" href="{% static 'core/vendors/owl-carousel/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'core/vendors/owl-carousel/css/owl.theme.default.css' %}">

    <!-- Bootstrap + Ollie main styles -->
	<link rel="stylesheet" href="{% static 'core/css/ollie.css' %}">

</head>
<body data-spy="scroll" data-target=".navbar" data-offset="40" id="home">

    <nav id="scrollspy" class="navbar navbar-light bg-light navbar-expand-lg fixed-top" data-spy="affix" data-offset-top="20">
        <div class="container">
            <a class="navbar-brand" href="#"><img src="assets/imgs/brand.svg" alt="" class="brand-img"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">
                    {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'aseguradoraNMA:index' %}" class="nav-link">Inicio</a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'aseguradoraNMA:servicios' %}" class="nav-link">Servicios</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#about">Sobre Nosotros</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#contact">Contacto</a>
                    </li>
                    {% endif %}

					{% load templatetagname %}
                    {% if user.is_authenticated %}
                    {% if request.user|has_group:"Clientes" %} 

                    <li class="nav-item">
                        <a href="{% url 'aseguradoraNMA:index' %}" class="nav-link">Inicio</a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'aseguradoraNMA:servicios' %}" class="nav-link">Servicios</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'aseguradoraNMA:solicitar_asesoria' %}">Solicitar Asesoria</a>
                    </li> 

                    <li class="nav-item">
                        <a class="nav-link" href="#contact">Contacto</a>
                    </li>

					{% endif %}
                    {% endif %}

                    {% if request.user|has_group:"Profesionales" %} 
                    <li class="nav-item">
                        <a href="{% url 'aseguradoraNMA:index' %}" class="nav-link">Inicio</a>
                    </li>
                    {% endif %}

                    {% if request.user|has_group:"Profesionales" %} 
                    <li class="nav-item">
                        <a href="{% url 'aseguradoraNMA:servicios' %}" class="nav-link">Servicios</a>
                    </li>
                    {% endif %}

                    <!--<li class="nav-item">
                        <a class="nav-link" href="{% url 'aseguradoraNMA:registrar_usuario' %}">Registrar Profesional</a>
                    </li>-->

                    <!--{% if request.user|has_group:"Profesionales" %} 
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'aseguradoraNMA:mantenedor_usuario' %}">Gestion de Usuarios</a>
                    </li> 
                    {% endif %}-->

                    {% if request.user|has_group:"Profesionales" %} 
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'aseguradoraNMA:listar_capacitacion' %}">Planificar Capacitaciones</a>
                    </li> 
                    {% endif %}

                    {% if request.user|has_group:"Profesionales" %} 
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'aseguradoraNMA:mantenedor_visita' %}">Planificar Visitas</a>
                    </li> 
                    {% endif %}
                    {% if request.user|has_group:"Profesionales" %} 
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'aseguradoraNMA:mantenedor_asesoria' %}">Planificar Asesorias</a>
                    </li> 
                    {% endif %}

                {% if user.is_authenticated and user.is_staff %}

                <li class="nav-item">
                    <a href="{% url 'aseguradoraNMA:index' %}" class="nav-link">Inicio</a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'aseguradoraNMA:servicios' %}" class="nav-link">Servicios</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'aseguradoraNMA:mantenedor_profesional' %}">Listado de Profesionales</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'aseguradoraNMA:mantenedor_usuario' %}">Gestion de Usuarios</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'aseguradoraNMA:mantenedor_contrato' %}">Gestion de Contratos</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'aseguradoraNMA:listar_capacitacion' %}">Planificar Capacitaciones</a>
                </li> 

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'aseguradoraNMA:mantenedor_visita' %}">Planificar Visitas</a>
                </li> 

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'aseguradoraNMA:mantenedor_asesoria' %}">Planificar Asesorias</a>
                </li>
    

                {% endif %}


                    {% if user.is_authenticated %}
                   <li>
                <a href="#"> Usuario: {{ user.username }}</a>
                </li>
                
                <li>
                <a class="nav-link btn btn-primary" href="{% url 'aseguradoraNMA:logout' %}">Cerrar Sesion</a>
                </li>
                    {% endif %}

                    {% if not user.is_authenticated %}
                        <li class="nav-item ml-0 ml-lg-4">
                            <a class="nav-link btn btn-primary" href="{% url 'aseguradoraNMA:login' %}">Iniciar Sesión</a>
                        </li> 
                    {% endif %}

                    {% if not user.is_authenticated %}
                        <li class="nav-item ml-0 ml-lg-4">
                            <a class="nav-link btn btn-primary" href="{% url 'aseguradoraNMA:registro' %}">Registrarse</a>
                        </li> 
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

<br></br>
<br></br>
<br></br>

    <section class="section" id="about">

        <div class="container">

            <div class="row align-items-center mr-auto">
                <div class="col-md-4">
                    <h6 class="xs-font mb-0">Manten el ambiente de trabajo seguro.</h6>
                    <h3 class="section-title">Nuestros Servicios</h3>
                    <p>Nuestro servicio consiste en todo lo necesario para mantener en regla tu empresa, contamos con profesionales 
                        especializados los cuales realizan visitas, asesorias, capacitaciones, ademas, un centro de llamados el cual resolvera
                        todas tus dudas.
                    </p>
                    <p>Mensualmente realizamos reportes de los resultados de nuestra gestion realizada para ti, donde tendras en detalle
                        todos los servicios realizados durante el mes. Este reporte estara siempre disponible para ti, pero solo podras solicitarlo 1 vez al mes,
                        si deseas una actualizacion se te cobrara de forma extra.
                    </p>

                    <a href="javascript:void(0)">Valor Mensual del Servicio: $42.990</a>
                    <br></br>
                    <a href="{% url 'aseguradoraNMA:registro' %}" class="btn btn-primary btn-rounded">Solicitar Servicios</a>
                </div>
                <div class="col-sm-6 col-md-4 ml-auto">
                    <div class="widget">
                        <div class="icon-wrapper">
                            <i class="ti-calendar"></i>
                        </div>
                        <div class="infos-wrapper">
                            <h4 class="text-primary">2 visitas mensuales</h4>
                            <p>Revision de documentacion,
                            Condiciones de seguridad, etc.</p>
                        </div>
                    </div>
                    <div class="widget">
                        <div class="icon-wrapper">
                            <i class="ti-face-smile"></i>
                        </div>
                        <div class="infos-wrapper">
                            <h4 class="text-primary">Capacitaciones de seguridad</h4>
                            <p>Se deben programar con 15 dias de anterioridad.
                                Se realizan capacitaciones extra pero se cobran como extra en el mes que se soliciten.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4">
                    <div class="widget">
                        <div class="icon-wrapper">
                            <i class="ti-star"></i>
                        </div>
                        <div class="infos-wrapper">
                            <h4 class="text-primary">10 Asesorias</h4>
                            <p>Se realizan asesorias en caso de accidentes, fiscalizaciones de las
                                entidades fiscalizadoras, en la que se incluye visita a terreno, interaccion
                                con el fiscalizador, gestion de accidentes, propuestas de mejora y verificacion de
                                implementacion de las mejoras propuestas.

                            </p>
                        </div>
                    </div>
                    <div class="widget">
                        <div class="icon-wrapper">
                            <i class="ti-user"></i>
                        </div>
                        <div class="infos-wrapper">
                            <h4 class="text-primary">Centro de Llamados</h4>
                            <p>Se resuelven dudas de Lunes a Viernes de 9:00 hrs. a 18:00 hrs.</p>
                        </div>
                    </div>
                </div>
             </div>
        </div>
    </section>